services:
  bot:
    image: ${DOCKER_REPO}/everlastingechobot
    container_name: everlastingechobot
    volumes:
      - ${MESSAGES_FOLDER}:/app/data
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 everlastingechobot